import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  module1Sidebar: [{type: 'autogenerated', dirName: 'module1-ros2'}],
  module2Sidebar: [{type: 'autogenerated', dirName: 'module2-digital-twin'}],
  module3Sidebar: [{type: 'autogenerated', dirName: 'module3-perception-control'}],
  module4Sidebar: [{type: 'autogenerated', dirName: 'module4-vla'}],
};

export default sidebars;